version: '3'
services:
    mongo_api:
        build: .
        restart: always
        image: 0.0.0.0:5050/mongo_api 
        ports:
            - "5000:5000"
        depends_on:
            - mongo_db
            - images
        links:
            - mongo_db

    mongo_db:
        restart: always 
        image: mongo
        ports:
            - "27017:27017"
    images:
        restart: always
        image: registry
        ports:
            - "5050:5000"

    vizualizer:
        image: dockersamples/visualizer
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
        - "8080:8080"
