version: '3'

services:
    database_api:
        build: ./database_api_service
        image: 127.0.0.1:5050/database_api:database_api
        ports:
            - "5000:5000"
        depends_on:
            - database
            - images
        links:
            - database
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        networks:
            - database
        environment:
            - DATABASE_URL=database
            - DATABASE_PORT=27017 

    database:
        image: mongo
        ports:
            - "27017:27017"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        networks:
            - database

    images:
        image: registry
        ports:
            - "5050:5000"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.role==manager"

        networks:
            - database

    visualizer:
        image: dockersamples/visualizer
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
        - "8080:8080"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                  - "node.role==manager"

networks:
    database:
