version: '3'

services:
    database_api:
        build: ./database_api_service
        image: 127.0.0.1:5050/database_api:database_api
        ports:
            - "5000:5000"
        depends_on:
            - rs
            - rs1
            - rs2
            - rs3
            - images
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.role==worker"
        networks:
            - database
        environment:
            - DATABASE_URL=rs1
            - DATABASE_PORT=27017 

    rs1:
        image: mongo:4
        command: mongod --replSet "rs0"
        networks:
            - database
        ports:
            - "27017:27017"

    rs2:
        image: mongo:4
        command: mongod --replSet "rs0"
        networks:
            - database
        ports:
            - "27018:27017"    
    rs3:
        image: mongo:4
        command: mongod --replSet "rs0"
        networks:
            - database
        ports:
            - "27019:27017"

    rs:
        image: 127.0.0.1:5050/rs:rs
        build: ./mongors
        networks:
            - database
        deploy:
            restart_policy:
                condition: on-failure

    images:
        image: registry:2
        ports:
            - "5050:5000"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - "node.role==manager"

        networks:
            - database
        volumes:
            - images:/var/lib/registry

    visualizer:
        image: dockersamples/visualizer
        volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        ports:
        - "8080:8080"
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                  - "node.role==manager"

networks:
    database:

volumes:
    images:
