version: '3'
services:
    mongo_api:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - mongo_db
        links:
            - mongo_db

    mongo_db:
        image: mongo
        ports:
            - "27017:27017"

